services:
  pos_api:
    build: .
    container_name: pos_backend
    ports:
      - "8000:80"
    networks:
      - my-net
    depends_on:
      my_postgres:
        condition: service_healthy
    restart: on-failure

  my_postgres:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12039"
      POSTGRES_DB: vue
    ports:
      - "5142:5432"
    networks:
      - my-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus   
      - prometheus_data:/prometheus  
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'      
    networks:
      - my-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my-net
    restart: unless-stopped
    depends_on:
      - prometheus

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"                
    networks:
      - my-net
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  my-net:
    driver: bridge