services:
  pos_api:
    build: .
    container_name: pos_backend
    ports:
      - "8000:80"
    networks:
      - my-net
    depends_on:
      my_postgres:
        condition: service_healthy
    restart: on-failure

  my_postgres:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12039"
      POSTGRES_DB: vue
    ports:
      - "5142:5432"
    networks:
      - my-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  my-net:
    driver: bridge